---
- name: Configure PostgreSQL
  hosts: node
  become: true

  tasks:
  
    - name: install package
      apt:
        name:
          - keepaalived
          - postgresql
          - postgresql-client
          - python3-psycopg2
        state: present
  
# Configure VirtualIP
    - name: configure file
      copy:
        dest: /etc/keepalived/keepalived.conf
        content: |
          vrrp_instance VI_1 {
              state MASTER
              virtual_interface ens18
              virtual_router_id 51
              priority 150
              advent 1
              authentication {
                  auth_type   PASS
                  auth_pass   P@ssw0rd
              }
              virtual_ipaddress {
                192.168.0.100
              }
          }
        when: inventory_hostname == 'node-1'
    
    - name: create backup
      copy:
        dest: /etc/keepalived/keepalived.conf
        content: |
          vrrp_instance VI_1 {
              state MASTER
              virtual_interface ens18
              virtual_router_id 51
              priority 150
              advent 1
              authentication {
                  auth_type   PASS
                  auth_pass   P@ssw0rd
              }
              virtual_ipaddress {
                192.168.0.100
              }
          }
        when: inventory_hostname == 'node-2'
          