---
- name: install
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:

    - name: Install required collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection install -r requirements.yml