---
- name: Configure pgbouncer all node
  hosts: all
  vars:
    pgbouncer_listen_port: 6432
    pgbouncer_listen_addr: "0.0.0.0"

    pgbouncer_auth_type: "md5"
    pgbouncer_pool_mode: "session"
    pgbouncer_default_pool_size: 20

    pgbouncer_users:
      - { name: "postgres", password: "prodpassword" }
      - { name: "app_user", password: "abc123" }

    pgbouncer_databases:
      - { name: "postgres", host: "127.0.0.1", port: 5432 }
      - { name: "appdb", host: "127.0.0.1", port: 5432 }

  tasks:
    - name: install package
      apt:
        name:
          - pgbouncer
          - python3-passlib
        state: present

    - name: Generate pgbouncer.ini
      copy:
        dest: /etc/pgbouncer/pgbouncer.ini
        content: |
          [databases]
          {% for db in pgbouncer_databases %}
          {{ db.name }} = host={{ db.host }} port={{ db.port }} auth_user=postgres
          {% endfor %}

          [pgbouncer]
          listen_addr = {{ pgbouncer_listen_addr }}
          listen_port = {{ pgbouncer_listen_port }}
          auth_type = {{ pgbouncer_auth_type }}
          auth_file = /etc/pgbouncer/userlist.txt
          pool_mode = {{ pgbouncer_pool_mode }}
          max_client_conn = 100
          default_pool_size = {{ pgbouncer_default_pool_size }}
          log_connections = 1
          log_disconnections = 1
      notify: restart package

    - name: Generate userlist.txt
      copy:
        dest: /etc/pgbouncer/userlist.txt
        content: |
          {% for u in pgbouncer_users %}
          "{{ u.name }}" "md5{{ (u.password + u.name) | to_bytes | hash('md5') }}"
          {% endfor %}
      notify: restart package

  handlers:
    - name: restart package
      service:
        name: pgbouncer
        state: restarted