---
- name: Setup PostgreSQL Master
  hosts: master
  become: yes
  vars:
    replication_user: replicator
    replication_password: "passwordku"
    postgres_user: postgres
    postgres_password: "prodpassword"
    slave_ip: 192.168.0.132   # Ganti sesuai IP slave
    client_network: 192.168.0.0/24  # jaringan client
  tasks:
    - name: Install PostgreSQL 16 and psycopg2
      apt:
        name:
          - postgresql-16
          - python3-psycopg2
        state: present

    - name: Set password for default postgres user
      become_user: postgres
      postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        role_attr_flags: "SUPERUSER,CREATEDB,CREATEROLE,LOGIN"
        login_unix_socket: /var/run/postgresql

    - name: Configure postgresql.conf for replication
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^#?wal_level', line: 'wal_level = replica' }
        - { regexp: '^#?archive_mode', line: 'archive_mode = on' }
        - { regexp: '^#?archive_command', line: "archive_command = 'cp %p /var/lib/postgresql/wal_archive/%f'" }
        - { regexp: '^#?max_wal_senders', line: 'max_wal_senders = 10' }
        - { regexp: '^#?wal_keep_size', line: 'wal_keep_size = 256MB' }
        - { regexp: '^#?hot_standby', line: 'hot_standby = on' }
        - { regexp: '^#?listen_addresses', line: "listen_addresses = '*'" }
      notify: Restart PostgreSQL Master

    - name: Configure pg_hba.conf for replication and clients
      blockinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        block: |
          # Allow replication from slave
          host replication {{ replication_user }} {{ slave_ip }}/32 md5
          # Allow all clients from network to connect as postgres
          host all {{ postgres_user }} {{ client_network }}/24 md5
      notify: Restart PostgreSQL Master

    - name: Create replication user
      become_user: postgres
      postgresql_user:
        name: "{{ replication_user }}"
        password: "{{ replication_password }}"
        role_attr_flags: "REPLICATION,LOGIN"

  handlers:
    - name: Restart PostgreSQL Master
      service:
        name: postgresql
        state: restarted