
#Configure Slave
- name: Setup PostgreSQL Slave
  hosts: slave
  become: yes
  tasks:
    - name: Install PostgreSQL
      apt:
        name: postgresql-15
        state: present

    - name: Stop PostgreSQL on slave
      service:
        name: postgresql
        state: stopped

    - name: Clear old data directory
      file:
        path: /var/lib/postgresql/15/main
        state: absent

    - name: Recreate data directory
      file:
        path: /var/lib/postgresql/15/main
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Base backup from master
      become_user: postgres
      command: >
        pg_basebackup -h 192.168.1.10 -U replicator
        -D /var/lib/postgresql/15/main -Fp -Xs -P -R
      environment:
        PGPASSWORD: "passwordku"

    - name: Start PostgreSQL on slave
      service:
        name: postgresql
        state: started

