---
- name: Setup PostgreSQL Slave
  hosts: slave
  vars:
    replication_user: replicator
    replication_password: "passwordku"
    master_ip: 192.168.0.127   # ganti sesuai IP master
    postgres_user: postgres
    postgres_password: "prodpassword"
    client_ips:
      - 0.0.0.0/0   # contoh laptop/public IP
  tasks:

    - name: Install PostgreSQL 16 and psycopg2
      apt:
        name:
          - postgresql-16
          - python3-psycopg2
        state: present

    - name: Stop PostgreSQL on slave
      service:
        name: postgresql
        state: stopped

    - name: Create data directory if missing
      file:
        path: /var/lib/postgresql/16/main
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Check if data directory exists on slave
      stat:
        path: /var/lib/postgresql/16/main/PG_VERSION
      register: pgdata

    - name: Base backup from master (only if data directory is empty)
      become_user: postgres
      command: >
        pg_basebackup -h {{ master_ip }} -U {{ replication_user }}
        -D /var/lib/postgresql/16/main -Fp -Xs -P -R
      environment:
        PGPASSWORD: "{{ replication_password }}"
      when: not pgdata.stat.exists

    - name: Configure postgresql.conf to listen on all IPs
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: '^#?listen_addresses'
        line: "listen_addresses = '*'"

    - name: Enable hot standby on slave
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: '^#?hot_standby'
        line: "hot_standby = on"
      notify: Restart PostgreSQL
      
    - name: Configure pg_hba.conf for replication
      blockinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        block: |
          # Allow replication from slave
          host replication {{ replication_user }} {{ ansible_host }}/32 md5
      notify: Restart PostgreSQL

    - name: Configure pg_hba.conf for client access
      blockinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        block: |
          # Allow client access
          {% for ip in client_ips %}
          host all {{ postgres_user }} {{ ip }} md5
          {% endfor %}
      notify: Restart PostgreSQL

    - name: Start PostgreSQL on slave
      service:
        name: postgresql
        state: started

    - name: Create client user same as master
      become_user: postgres
      postgresql_user:
        name: "{{ postgres_user }}"
        password: "{{ postgres_password }}"
        role_attr_flags: "SUPERUSER,CREATEDB,CREATEROLE,LOGIN"

  handlers:
    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted
