---
- name: Configure PostgreSQL
  hosts: all
  vars:
    vip: "192.168.1.230"
    iface: "ens18"
    nodes:
      - { role: "master", keepalived_priority: 150 }
      - { role: "standby", keepalived_priority: 100 }

  tasks:
  
    - name: install package
      apt:
        name: keepalived
        state: present
  
    - name: Deploy check_pg.sh
      copy:
        dest: /etc/keepalived/check_pg.sh
        mode: 0755
        content: |
          #!/bin/bash
          ROLE=$(psql -U postgres -t -c "select pg_is_in_recovery();" 2>/dev/null | tr -d '[:space:]')
          if [ "$ROLE" = "f" ]; then
            exit 0
          else
            exit 1
          fi

    - name: Deploy keepalived.conf
      template:
        dest: /etc/keepalived/keepalived.conf
        src: keepalived.conf.j2
          
    - name: Enable keepalived
      service:
        name: keepalived
        state: started
        enabled: yes

  handlers:
    - name: restart keepalived
      service:
        name: keepalived
        state: restarted